### ISSUE TITLE
Add user setting for using builtin Stylus built-in functions

### ISSUE THREAD

**Issue by tomquirk** [d4rkr00t/language-stylus#18]
Would be nice to provide users with an option to opt out of using the built in Stylus functions for autocompletion. 

Something like `"languageStylus.useBuiltinFunctions": false`

**Comment by d4rkr00t** [comment]
Hi,

Looks interesting. Definitely worth adding. I'll do it.

**Comment by tomquirk** [comment]
I've done it, Ill submit a pull request now :)

**Comment by d4rkr00t** [comment]
Great!

**Comment by d4rkr00t** [comment]
Fixed here https://github.com/d4rkr00t/language-stylus/pull/19
