### ISSUE TITLE
Don't open autocomplete suggestions after open curly braces

### ISSUE THREAD

**Issue by ghost** [d4rkr00t/language-stylus#2]
Every time that we open a curly brace the pop up with the autocompletion suggestion come up.
It's pretty annoying because I always hit enter just after open the brace and I end up accepting the firts suggestion on list..
Is there a way to revert it?

**Comment by d4rkr00t** [comment]
Hi, I added curly braces as trigger characters, I don't know why :). I'll revert it. Thank you for report.
