### ISSUE TITLE
Add autoclosing pairs for quotes

### ISSUE THREAD

**Issue by ghost** [d4rkr00t/language-stylus#3]
Do you have any objections about adding support to autoclosing quotes?

**Comment by d4rkr00t** [comment]
Hi, thank you for feature request.

I haven't thought about it. But it definitely useful feature. I'll take a look, maybe there is a way to enable this feature for custom languages in vscode or I'll try to implement it soon, but I can't promise any particular date.

**Comment by ghost** [comment]
actually it's pretty simple.
just add this in `stylus.configuration.json`

``` json
"autoClosingPairs": [
    ["{", "}"],
    ["[", "]"],
    ["(", ")"],
    ["\"", "\""],
    ["'", "'"]
]
```

And this could also be helpful, I don't know exactly what this does but the default language extensions have it

``` json
"surroundingPairs": [
    ["{", "}"],
    ["[", "]"],
    ["(", ")"],
    ["\"", "\""],
    ["'", "'"]
]
```

**Comment by d4rkr00t** [comment]
Great! You can send pr or I'll make it later today.

**Comment by ghost** [comment]
OK. But first I've two questions:
1. there is a .editorconfig file defining all indententions to 2 spaces, but all the json files have 4 spaces, is that an expected formatting or I little mistake? My editor is going crazy with this, rs
2. Is there any test that I should run? I took a look a the test files but those seems to be the autogenerated.

**Comment by d4rkr00t** [comment]
1. It's my mistake, it should be 2 spaces everywhere.
2. There aren't any tests yet.

**Comment by ghost** [comment]
Ok I'll convert to 2 spaces ok? And sorry in advance for any mistake that I come to do.I'm prettty new in this github stuff..

**Comment by d4rkr00t** [comment]
Yep, if you convert it'd be great. And never mind about any mistake :).

**Comment by ghost** [comment]
I've just made the PR. Do you know I'm not getting intellisense and snippets completions when I run the extension locally, by putting my cloned repo directly insinde my extensions folder? I'm afraid I'm doing something very wrong that could brake something

**Comment by d4rkr00t** [comment]
Let's continue in PR.
