### ISSUE TITLE
How can I use this effect for .vue file,not only styl files?

### ISSUE THREAD

**Issue by gogir** [d4rkr00t/language-stylus#30]
I work use vue.Is there have any configeration to set file extname?

![image](https://cloud.githubusercontent.com/assets/9463604/20858324/7feb3184-b97e-11e6-8630-95e087a418f4.png)

**Comment by d4rkr00t** [comment]
Hi, there aren't any configuration for file types. But i'll try to figure it out. 

Does css highlighting work there?

**Comment by gogir** [comment]
Thanks for your replay, css highlighting is  worked fine.

**Comment by d4rkr00t** [comment]
ok, that's pretty wired, I'll try it myself as soon as i come back from the business trip :) And i let you know if i'll be able to work something out.

**Comment by asifm** [comment]
Any update on this? I really would appreciate if you could make this work.

**Comment by d4rkr00t** [comment]
Unfortunately no, I tried but it seems like vue extension has everything built in. And there is no way to add another syntax highlighting there.
