### ISSUE TITLE
No : with Emmet

### ISSUE THREAD

**Issue by sjelfull** [d4rkr00t/language-stylus#32]
It does not look like Emmet uses `:`

![screencast 2016-12-13 at 11 37 15 am](https://cloud.githubusercontent.com/assets/10508/21137102/b42ba85a-c128-11e6-9473-5536717bffc8.gif)

Related to #16

**Comment by d4rkr00t** [comment]
Hi, yes i know, emmet doesn't use semicolon. It'd be awesome if they had an option to turn on semicolons in syntaxes like stylus.

**Comment by sjelfull** [comment]
@d4rkr00t Should I file this for Emmet, or do you have an idea how we can fix this?

**Comment by sjelfull** [comment]
Hurrah. This is fixable by adding the following to user preferences:

    "emmet.preferences": {
        "stylus.propertyEnd": ";",
        "stylus.valueSeparator": ": "
    }

**Comment by d4rkr00t** [comment]
Wow, thanks! Didn't know that :).
