### ISSUE TITLE
Disable quickSuggestions in setting

### ISSUE THREAD

**Issue by exdeniz** [d4rkr00t/language-stylus#33]
Is it possible to disable editor.quickSuggestions for stylus files?

**Comment by d4rkr00t** [comment]
Hm, do you want to disable all suggestions for stylus files including provided by this extensions or you just want to disable built-in vscode suggestions?

**Comment by exdeniz** [comment]
I wish that would work correctly emmet. VS Code developer recommend to disable editor.quickSuggestions for it. I just want on db -> display block...

**Comment by d4rkr00t** [comment]
Hm that should work properly. I usually want exact opposite.

**Comment by exdeniz** [comment]
example: http://giphy.com/gifs/26FLbhkRnkJtNrhss

**Comment by d4rkr00t** [comment]
Oh, ok, i see. You want to disable autocompletion items which come from this extensions right?

I could think about option to disable them, or i can respect option editor.quickSuggestions to disable autocompletion.

Does it sound good?

**Comment by exdeniz** [comment]
Yes, on open/edit stylus file editor.quickSuggestions toggle off and other file editor.quickSuggestions - on. It's possible?

**Comment by d4rkr00t** [comment]
I think this is not possible.

**Comment by exdeniz** [comment]
=( I will wait solve problem with emmet and quickSuggestions from VS Code developers. Thanks

**Comment by d4rkr00t** [comment]
Thank you for the report. Closing this :)
