### ISSUE TITLE
Investigate indentation issue

### ISSUE THREAD

**Issue by d4rkr00t** [d4rkr00t/language-stylus#45]
> Btw, no way to auto add one indent after for example a class, id or element is written? (This is the behavior in Brackets/Atom)
> 
> e.g. With an enter should be 
> ```
> .hola
>   width 3px
> ```
>
> But it currently is
> ```
> .hola
> width 3px
> ```
> 
>  It doesn't recognize that next will be a property so it should have one indent, it's something really small but I really like how fast it is in other IDE when the extension adds that indent after each element when going to the next line.

**Comment by octref** [comment]
Just saying this is what you are looking for:
`vscode.languages.setLanguageConfiguration('stylus', { indentationRules }`

**Comment by d4rkr00t** [comment]
I solved some of the cases, but it's hard because of the nature of stylus syntax to write regexps that cover all the cases :(

**Comment by WoodyWoodsta** [comment]
I use stylus with full punctuation i.e. curly braces, which one could argue as being 100% acceptable. I now have the annoying cases where the closing curly brace is being indented when I hit enter.

Intention
```css
.my-class {
}
```

Actual result
```css
.my-class {
  }
```

**Comment by hackuun** [comment]
@octref how to use it? WHere shouls I paste this settings? How to autoindent?
