### ISSUE TITLE
Color picker doesn't work in stylus file (*.styl), maybe it only work in *.css file.

### ISSUE THREAD

**Issue by aeschli** [d4rkr00t/language-stylus#51]
_From @vimcaw on August 17, 2017 1:37_

- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
yaml|ada|0.0.7
markdown-preview-github-styles|bie|0.0.2
regex|chr|0.1.0
vscode-hexo|cod|1.0.1
vscode-html-css|ecm|0.1.7
hexo-tag-snippets|max|0.1.7
cpptools|ms-|0.12.2
ejs-language-support|Qas|0.0.1
vscode-icons|rob|7.12.0
language-stylus|sys|1.7.3
ejs-snippets|Tao|0.1.0
open-in-browser|tec|1.1.0
vscode-arduino|vsc|0.2.4
JavaScriptSnippets|xab|1.4.1

(1 theme extensions excluded)

---

Steps to Reproduce:

Color picker doesn't work in stylus file (*.styl), maybe it only work in *.css file.

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#32678_

**Comment by aeschli** [comment]
The language-stylus has to adopt the color decoration provider. That said, the API is still in the 'proposed' state.

**Comment by d4rkr00t** [comment]
Yeah, thanks, I have that in plans :)

**Comment by rajinder-yadav** [comment]
Issue Type: Bug

Colour preview works, however the colour-picker fails to show for ".styl" files.

![screen shot 2018-02-25 at 5 19 13 pm](https://user-images.githubusercontent.com/439226/36647198-0d7b27ce-1a50-11e8-8175-2b1fe5420205.png)

VS Code version: Code - Insiders 1.21.0-insider (ce13bb0dabd06981913c46b5a94456647864c2e0, 2018-02-23T06:08:53.779Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron . .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
ng-template|Ang|0.1.9
vscode-markdownlint|Dav|0.13.0
EditorConfig|Edi|0.12.1
npm-intellisense|chr|1.3.0
tslint|eg2|1.0.28
Go|luk|0.6.77
angular2-inline|nat|0.0.17
language-stylus|sys|1.9.1
vim|vsc|0.10.13
markdown-pdf|yza|0.1.7


</details>
Reproduces only with extensions

**Comment by d4rkr00t** [comment]
Yeah, as far as i remember it's not supported yet :)

**Comment by rajinder-yadav** [comment]
Would love to see this added when possible, thanks!

**Comment by davemoz** [comment]
+1

**Comment by luisDanielRoviraContreras** [comment]
+1

**Comment by V1raNi** [comment]
+1, definitely need this feature

**Comment by rayosdev** [comment]
+1 it's great for prototyping

**Comment by AdnanBabakan** [comment]
+1 definitely need it, stylus is much better than Sass

**Comment by Ne4to777** [comment]
+1

**Comment by VCourdy** [comment]
+1

**Comment by JohnDeved** [comment]
there is still no update to this? why is it so hard to implement?

**Comment by d4rkr00t** [comment]
@JohnDeved if it looks this easy, or you have got time to do it, PRs are welcome :)

**Comment by VCourdy** [comment]
@JohnDeved this point need a major refactor of the project.
As far as i know you must change the project structure in order to be a "LTE", you should read about this [here](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) if you want to contribute ;)

**Comment by realwumbl3** [comment]
bump??? am I allowed to do that? I wanna see this plssss

**Comment by d4rkr00t** [comment]
I'll have a look if there is a quick way to do it. Not sure though. Also @realwumbl3 if you want to give it a try, I'd be more than happy to review a PR :)

**Comment by sirkouga** [comment]
+1 please
