### ISSUE TITLE
Conflict with the editor.colorDecorators setting

### ISSUE THREAD

**Issue by xthezealot** [d4rkr00t/language-stylus#53]
When this extension is enabled and after I open a Stylus file, the `editor.colorDecorators` custom setting is definitively suppressed, even for pure CSS files.

The setting :

![Setting](https://user-images.githubusercontent.com/9503891/30391644-763c767c-98ba-11e7-81da-56d8a890d97f.png)

language-stylus disabled or until I open a Stylus file for the first time:

![language-stylus disabled](https://user-images.githubusercontent.com/9503891/30391841-2a4c5fec-98bb-11e7-92a3-b841d16b3fab.png)

language-stylus enabled and after a Stylus file has been opened for the first time:

![language-stylus enabled](https://user-images.githubusercontent.com/9503891/30391750-e12e1346-98ba-11e7-864c-d47f482984cc.png)

At a glance, maybe the [updateDecorators](https://github.com/d4rkr00t/language-stylus/blob/a7074d68dd3a7c88760c0d87b5e50042e892124f/src/color-decorators.ts#L89) function should check for the user settings.

**Comment by d4rkr00t** [comment]
Wow, thanks for the report, I wonder how's that even possible? :) Anyway, I'll take a look.
