### ISSUE TITLE
Color preview squares newline bug 

### ISSUE THREAD

**Issue by sparcut** [d4rkr00t/language-stylus#55]
I don't personally use the built-in vs code color previews, but when they are enabled they act funny in multi-line hash with new lines.

See screenshot below for bug.

![code_2017-12-03_10-21-02](https://user-images.githubusercontent.com/16233822/33520672-af40ee74-d813-11e7-8821-9d6b9ce7d519.png)

**Comment by iChenLei** [comment]
already fixed.
