### ISSUE TITLE
Missing New CSS Grid Support

### ISSUE THREAD

**Issue by mattwaler** [d4rkr00t/language-stylus#62]
Syntax highlighting for CSS Grid spec does not highlight correctly. I have attached a screenshot to help.

![screen shot 2018-03-15 at 4 40 51 pm](https://user-images.githubusercontent.com/32300026/37489957-a5de53f6-286f-11e8-8a90-cb9862b95241.png)

**Comment by MartinMuzatko** [comment]
I don't get why stylus can't use the default css properties and has to maintain its own list.
However, this would be very much appreciated.

**Comment by ErickPetru** [comment]
The [CSS Grid Layout Module](https://www.w3.org/TR/css-grid-1/) is in _Candidate Recommendation_ for a while now and VS Code already recognizes its properties very well. But **language-stylus** still show as unknow properties. Here's the list of the new properties to be added to the recognized ones:

```
column-gap
gap
grid
grid-area
grid-auto-columns
grid-auto-flow
grid-auto-rows
grid-column
grid-column-end
grid-column-start
grid-row
grid-row-end
grid-row-start
grid-template
grid-template-areas
grid-template-columns
grid-template-rows
row-gap
```

**Comment by ErickPetru** [comment]
Please merge pull request #66 to add the properties.

**Comment by mattwaler** [comment]
@ErickPetru is there any way for me to get this working in my VS code until the request gets merged?

**Comment by ErickPetru** [comment]
@mattwaler you can get a local copy of this reposity and update the line 414 as I did here: https://github.com/d4rkr00t/language-stylus/pull/66/files. Then, unsubscribe from the official extension and add your local copy as an extension (here's the documentation about it: https://vscode-docs.readthedocs.io/en/stable/extensions/install-extension/). The proccess is a little overwelming and for sure you stop receiving updates from the official extension, so I don't recommend.

**Comment by mattwaler** [comment]
@ErickPetru Gotcha, I'll just wait for the merge. Thanks for your help!

**Comment by d4rkr00t** [comment]
Merged: https://github.com/d4rkr00t/language-stylus/pull/66
