### ISSUE TITLE
bug: color preview square show twice on CSS files

### ISSUE THREAD

**Issue by yukulele** [d4rkr00t/language-stylus#65]
color preview square show twice on CSS files,
this bug only occurs if a stylus file is open in other tab.

**Comment by nibk** [comment]
On the current version 1.14.0 the colored squares show 16 times

![image](https://user-images.githubusercontent.com/74578972/143327789-cd74b377-4970-4b48-87d6-60dfad3e3937.png)

**Comment by iChenLei** [comment]
@nibk  ~~Can you provide reproducation stylus code snippet ?~~
