### ISSUE TITLE
Import browser data from css-language-service

### ISSUE THREAD

**Issue by octref** [d4rkr00t/language-stylus#69]
Hey @d4rkr00t, this is Pine from VS Code team. I work on https://github.com/Microsoft/vscode-css-languageservice and https://github.com/vuejs/vetur. Recently I got this PR: https://github.com/vuejs/vetur/pull/953, so I thought I should upstream it.

I have made a lot of improvements to `browsers.ts` in the last few months, using data from MDN. Would be great to see these changes propagate to Stylus in a similar way: https://code.visualstudio.com/updates/v1_25#_new-css-pseudo-selectors-and-pseudo-elements-from-mdn

Here's a rough plan:
- Add `css-languageservice` as a dependency.
- Start to add things such as browser compatibility data, css property syntax to the completion items.

What do you think? I can work on PRs.

**Comment by d4rkr00t** [comment]
Hey, sounds awesome! I'm not actively maintain this extensions anymore, but i'm happy to accept PRs :)

**Comment by octref** [comment]
![stylus](https://user-images.githubusercontent.com/4033249/50124248-a9a2cc00-0218-11e9-97e1-925545d065e6.gif)

PR is at #70.

**Comment by octref** [comment]
Fixed and shipped.
