### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by DMalagonH** [d4rkr00t/language-stylus#71]
- Issue Type: `Performance`
- Extension Name: `language-stylus`
- Extension Version: `1.11.0`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/diego/sysoev.language-stylus-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by iChenLei** [comment]
duplicated #76
