### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by arieaditya** [d4rkr00t/language-stylus#72]
- Issue Type: `Performance`
- Extension Name: `language-stylus`
- Extension Version: `1.11.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/arieaditya/sysoev.language-stylus-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by iChenLei** [comment]
Duplicated #71
