### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by the94air** [d4rkr00t/language-stylus#73]
- Issue Type: `Performance`
- Extension Name: `language-stylus`
- Extension Version: `1.11.0`
- OS Version: `Linux x64 4.18.0-16-generic`
- VSCode version: `1.32.0`

:warning: [sysoev.language-stylus-unresponsive.cpuprofile.txt](https://github.com/d4rkr00t/language-stylus/files/2970485/sysoev.language-stylus-unresponsive.cpuprofile.txt) :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by iChenLei** [comment]
Duplicated #71
