### ISSUE TITLE
Nested tags (built-ins) with pseudo classes do not get formatted correctly

### ISSUE THREAD

**Issue by pqvst** [d4rkr00t/language-stylus#74]
Nested tags (built-ins) with pseudo classes do not get formatted correctly. Note however that classes and non-nested tags do get formatted correctly.

![image](https://user-images.githubusercontent.com/4990657/56739662-87ddc680-676f-11e9-965c-2092d9909520.png)

```
.child
.child:hover
.child.toggle
label
label:hover
label.toggle

.parent
  .child
  .child:hover
  .child.toggle
  label
  label:hover     /* broken */
  label.toggle
```

**Comment by iChenLei** [comment]
Duplicated #75
