### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AndreiJam** [d4rkr00t/language-stylus#76]
- Issue Type: `Performance`
- Extension Name: `language-stylus`
- Extension Version: `1.11.0`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/ayemia/sysoev.language-stylus-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by shepelevstas** [comment]
Same here!

**Comment by shepelevstas** [comment]
4 open issues about high cpu and no replies!? Is the extension abandoned?

**Comment by d4rkr00t** [comment]
Yes, this extension is not actively maintained, as I'm not using stylus anymore, and because stylus itself is not maintained, last release was 3 years ago. 

If you have ideas, or want to improve this extension PRs are more than welcome.

**Comment by iChenLei** [comment]
- Issue Type: `Bug`
- Extension Name: `language-stylus`
- Extension Version: `1.11.0`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.42.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 9765,
		"activateCallTime": 30,
		"activateResolvedTime": 166,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "sysoev.language-stylus",
				"_lower": "sysoev.language-stylus"
			},
			"activationEvent": "onLanguage:stylus"
		}
	},
	"runtimeErrors": []
}
```
> From issue #79
