### ISSUE TITLE
Syntax highlighting inside js

### ISSUE THREAD

**Issue by Pytal** [d4rkr00t/language-stylus#78]
Could you extend the Stylus syntax highlighing to work when Stylus syntax is written inside js, similar to how [styled-components](https://github.com/styled-components/vscode-styled-components) syntax highlighting works?

**Comment by iChenLei** [comment]
Sorry, It's out of scope. If you need css-in-js highlight, it means css-in-js library is better choice for css solution. We don't know how to detect content which need highlight, all [`template literals`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) in js(x)/ts(x)? and also cause conflict with other vscode extension which represent js(x)/ts(x) file. so close this issue.
