### ISSUE TITLE
Can't find on VS Codium market place

### ISSUE THREAD

**Issue by rathod-sahaab** [d4rkr00t/language-stylus#80]

**Comment by rathod-sahaab** [comment]
![Screenshot from 2020-08-14 04-30-50](https://user-images.githubusercontent.com/31929374/90195453-0b994780-dde7-11ea-818b-cdd3b7229f5b.png)

**Comment by d4rkr00t** [comment]
Hm, weird, seems to be working fine for me. But thanks for letting me know, i'll keep an eye on it.

**Comment by rathod-sahaab** [comment]
Sorry I mentioned VS Code intstead of **VS Codium**, other exts work fine

**Comment by d4rkr00t** [comment]
Oh, with vscodium i can reproduce it

**Comment by d4rkr00t** [comment]
https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace

**Comment by d4rkr00t** [comment]
I'll have a look at publishing it there a bit later today :)

**Comment by noraj** [comment]
It's no longer in the VS Code marketplace either.

**Comment by d4rkr00t** [comment]
https://marketplace.visualstudio.com/items?itemName=sysoev.language-stylus

**Comment by noraj** [comment]
@d4rkr00t Yes it's in the marketplace but no instalable via VSCode extension browser directly.

![image](https://user-images.githubusercontent.com/16578570/97354755-2cc1ee00-1896-11eb-9a4f-38bb6ddb9b49.png)
![image](https://user-images.githubusercontent.com/16578570/97354827-43684500-1896-11eb-830d-1c8c9982104f.png)

`ext install sysoev.language-stylus` doesn't work either.

A lot of extensions disappeared recently (those last weeks or months), I there a new extension system? or maybe the extension is not compatible with the last versions of VSCode.

```
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-15T10:42:48.064Z
Electron: 9.3.2
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.1-arch1-1
```

**Comment by rathod-sahaab** [comment]
Yeah I guess there is some issue, @noraj meanwhile you can install from .vsix download from [Language Stylus 1.11.0](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/sysoev/vsextensions/language-stylus/1.11.0/vspackage)

For further instruction make a quick search

**Comment by rathod-sahaab** [comment]
[https://aur.archlinux.org/packages/vscodium-marketplace](https://aur.archlinux.org/packages/vscodium-marketplace)

This package fixed this issue for me @iChenLei
