### ISSUE TITLE
@apply is unknown property.

### ISSUE THREAD

**Issue by x-ray-s** [d4rkr00t/language-stylus#82]
`@apply rules` is an unknown property, so the highlight is not working.

**Comment by iChenLei** [comment]
@apply spec is Abandoned, please don't use it

https://www.xanthir.com/b4o00
https://tabatkins.github.io/specs/css-apply-rule/#using
https://caniuse.com/?search=%40apply
https://github.com/microsoft/vscode-css-languageservice/commit/8c480de9461f51112bf4f58e4add4d390845eaf6

**Comment by Anaphase** [comment]
For people using Tailwind's `@apply` directive, you can install the [Tailwind CSS IntelliSense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) for support.
