### ISSUE TITLE
feature request: color preview swatches

### ISSUE THREAD

**Issue by axefrog** [d4rkr00t/language-stylus#9]
[VS Code now supports color preview swatches](https://code.visualstudio.com/docs/languages/css):

![image](https://cloud.githubusercontent.com/assets/298883/17122153/6479d748-531c-11e6-9768-2cb422ee0cd1.png)

It'd be nice to see this in Stylus files too. Currently I see this kind of thing, which is harder to work with:

![image](https://cloud.githubusercontent.com/assets/298883/17122138/4c6ae854-531c-11e6-85e4-e6b85ea46803.png)

![image](https://cloud.githubusercontent.com/assets/298883/17122177/8960cfbc-531c-11e6-8d90-b6e4a0f2a0ba.png)

**Comment by d4rkr00t** [comment]
Hi, thanks for feedback. This feature is in my todo list :) I'll prioritize it a bit since you're interested in it.

**Comment by davidyezsetz** [comment]
Would love to see that, too.
Thanks for the effort :)

**Comment by Akiyamka** [comment]
In the to-do list it is written that there is some 'hacky' way for fix that. Could you tell me which one?

**Comment by d4rkr00t** [comment]
I was thinking about some hacky way back then, but i can remember now, and it doesn't matter anymore since vscode team has added Decorators.

**Comment by d4rkr00t** [comment]
Example of color decorator from css extension: https://github.com/Microsoft/vscode/blob/master/extensions/css/client/src/colorDecorators.ts
