### ISSUE TITLE
Color preview not functioning properly when using hex values

### ISSUE THREAD

**Issue by AlekEagle** [d4rkr00t/language-stylus#96]
Color previews seem to break when using hex to define a color.
![example of bug](https://you-have-a.shit.computer/Q3P5lnHIyj.png)
I do use SynthWave '84, however, the modification from the extension does not affect the color preview in any other language, so I have come to believe that the bug stems from the addon itself.

**Comment by iChenLei** [comment]
@AlekEagle  Thanks for bug report.

![2021-12-06 10 27 16](https://user-images.githubusercontent.com/14012511/144777440-e59290a2-75b3-4158-867c-a902fa86b598.png)

I reproduce it, will try to fix next weeks.

**Comment by g191091788** [comment]
@iChenLei 
```stylus
create_attr()
  for key,value in $attrs
    // 这可行吗
    {key}:value unless @{key};

```
